server.port=8083
spring.datasource.url=jdbc:mysql://localhost:3306/homefix_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Aayush@2007
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true